apiVersion: agents.contrastsecurity.com/v1beta1
kind: ClusterAgentConfiguration
metadata:
  name: default-agent-configuration
  namespace: contrast-agent-operator
spec:
  template:
    spec:
      yaml: |
        protect:
          enable: true
        assess:
          enable: true
        observe:
          enable: true
        agent:
          logger:
            level: INFO
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: ClusterAgentConnection
metadata:
  name: default-agent-connection
  namespace: contrast-agent-operator
spec:
  template:
    spec:
      token:
        secretName: default-agent-connection-secret
        secretKey: token
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: contrast-flex-injector
  namespace: default
spec:
  enabled: true
  type: flex
  selector:
    images:
      - "*"
    labels:
      - name: contrast-agent
        value: flex
