apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.exploitserver.name }}"
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.exploitserver.name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.exploitserver.name }}
    spec:
      containers:
        - name: {{ .Values.exploitserver.name }}
          image: {{ .Values.exploitserver.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1389
              name: ldap
            - containerPort: 8180
              name: http
            - containerPort: 9999
              name: rmi
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: exploit-server
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  selector:
    app: {{ .Values.exploitserver.name }}
  ports:
    - protocol: TCP
      name: ldap
      port: 1389
      targetPort: 1389
    - protocol: TCP
      name: http
      port: 8180
      targetPort: 8180
    - protocol: TCP
      name: rmi
      port: 9999
      targetPort: 9999
