apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulation-console-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: zapproxy.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zapproxy
                port:
                  number: 80
    - host: console.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console-ui
                port:
                  number: 5000
