apiVersion: v1
kind: ServiceAccount
metadata:
  name: modsecurity-crs-proxy-sa
---
apiVersion: v1
kind: Service
metadata:
  name: modsecurity-crs-proxy
  labels:
    app.kubernetes.io/instance: modsecurity-crs-proxy
    app.kubernetes.io/name: modsecurity-crs-proxy
spec:
  selector:
    app.kubernetes.io/instance: modsecurity-crs-proxy
    app.kubernetes.io/name: modsecurity-crs-proxy
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modsecurity-crs-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: modsecurity-crs-proxy
      app.kubernetes.io/name: modsecurity-crs-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: modsecurity-crs-proxy
        app.kubernetes.io/name: modsecurity-crs-proxy
    spec:
      containers:
      - env:
        - name: BACKEND
          value: http://frontgateservice.cargo-cats.svc.cluster.local:8081
        - name: PORT
          value: "8080"
        - name: ROUTE_INGRESS_PORT
          value: "443"
        - name: ROUTE_INGRESS_PROTOCOL
          value: "https"
        - name: SERVER_TOKENS
          value: "off"
        - name: MODSEC_RULE_ENGINE
          value: DetectionOnly
        - name: PARANOIA
          value: "3"
        - name: BLOCKING_PARANOIA
          value: "3"
        - name: CORS_HEADER_403_CONTENT_TYPE
          value: text/html
        - name: MODSEC_RESP_BODY_LIMIT
          value: "10485760"
        image: owasp/modsecurity-crs:4.20.0-nginx-alpine-202511100111
        imagePullPolicy: IfNotPresent
        name: modsecurity-crs-proxy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: true
          runAsGroup: 101
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: modsecurity-crs-proxy-sa
      terminationGracePeriodSeconds: 30
