apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysctl-tuner
  namespace: openshift-operators
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuner
  namespace: openshift-operators
spec:
  selector:
    matchLabels:
      app: sysctl-tuner
  template:
    metadata:
      labels:
        app: sysctl-tuner
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          echo 262144 > /proc/sys/vm/max_map_count
          while true; do sleep 3600; done
        image: registry.access.redhat.com/ubi8/ubi-minimal
        imagePullPolicy: IfNotPresent
        name: sysctl-tuner
        resources: {}
        securityContext:
          runAsUser: 0
          privileged: true
      hostNetwork: true
      serviceAccount: sysctl-tuner
