---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-{{ .Values.frontgateservice.name }}'
  namespace: {{ .Release.Namespace }}
  labels:
    contrast-agent: flex
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontgateservice.name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.frontgateservice.name }}
    spec:
      containers:
        - name: {{ .Values.frontgateservice.name }}
          image: {{ .Values.frontgateservice.image }} 
          imagePullPolicy: Never
          env:
          - name: CONTRAST__APPLICATION__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.frontgateservice.name }}'
          - name: CONTRAST__SERVER__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.frontgateservice.name }}-agent'
          - name: SPRING_DATASOURCE_URL
            value: 'jdbc:mysql://{{.Release.Name}}-db:3306/{{ .Values.mysql.database }}?createDatabaseIfNotExist=true'
          - name: SPRING_DATASOURCE_USERNAME
            value: '{{ .Values.mysql.user }}'
          - name: SPRING_DATASOURCE_PASSWORD
            value: '{{ .Values.mysql.password }}'
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
          readinessProbe:
            httpGet:
              path: /login
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontgateservice.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.frontgateservice.name }}
  ports:
    - name: http-port      
      protocol: TCP
      port: 8081           
      targetPort: 8081     


---
