apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{.Release.Name}}-{{ .Values.imageservice.name }}-sa'
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "contrast-cargo-cats.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-{{ .Values.imageservice.name }}'
  namespace: {{ .Release.Namespace }}
  labels:
    contrast-agent: flex
spec:
  selector:
    matchLabels:
      app: {{ .Values.imageservice.name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.imageservice.name }}
    spec:
      #serviceAccount: {{ include "contrast-cargo-cats.serviceAccountName" . }}
      serviceAccount: '{{.Release.Name}}-{{ .Values.imageservice.name }}-sa'
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end}}
      containers:
        - name: {{ .Values.imageservice.name }}
          image: "{{ .Values.imagePrefix }}{{ .Values.imageservice.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: CONTRAST__APPLICATION__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.imageservice.name }}'
          - name: CONTRAST__SERVER__NAME
            value: '{{ .Values.contrast.uniqName }}-{{.Release.Name}}-{{ .Values.imageservice.name }}-agent'
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imageservice.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.imageservice.name }}
  ports:
    - name: http-port      
      protocol: TCP
      port: 80           
      targetPort: 80     


---
