{{- if .Values.createRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cargocats
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.frontgateservice.name }}
  port:
    targetPort: http-port
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: opensearch-dashboard
  port:
    targetPort: 5601
  tls:
    termination: edge
{{- end }}